baseURL = "https://liangsam.github.io"
languageCode = "en"
title = "梁某银的Blogs"
theme = "paper"

[params]
  color = 'linen'

  twitter = 'https://twitter.com/chandlefans'

  avatar = 'https://github.com/LiangSam/liangsam.github.io/blob/main/content/%E4%B8%AA%E4%BA%BA%E5%A4%B4%E5%83%8F.png?raw=true'
  name = 'Liang'
  bio = '努力探索'

# needed to  render raw HTML (e.g. <sub>, <sup>, <kbd>, <mark>)
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[menu]

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 10
